// Creates the Angular environment files.
//
// These files are NOT stored in Git. They are generated fresh every time
// you run "npm start" or "npm run build" - including inside GitHub Actions,
// where the values come from GitHub Secrets.

const fs = require('fs');
const path = require('path');

const folder = path.join('src', 'environments');

// process.env holds the environment variables of the current machine.
// In GitHub Actions these are filled in from GitHub Secrets.
//
// .trim() removes stray spaces and line breaks. A secret pasted with a
// trailing newline would otherwise be written straight into the file and
// break the TypeScript string.
const apiUrl = (process.env.API_URL || 'http://localhost:3000').trim();
const appEnv = (process.env.APP_ENV || 'development').trim();

// The folder is ignored by Git, so on a fresh clone it does not exist yet.
fs.mkdirSync(folder, { recursive: true });

// JSON.stringify wraps the value in quotes AND escapes anything unsafe,
// so the generated file is always valid TypeScript.
const devFile = `// AUTO-GENERATED by generate-env.js. Do not edit. Do not commit.
export const environment = {
  apiUrl: ${JSON.stringify('http://localhost:3000')},
  appEnv: ${JSON.stringify('development')}
};
`;

const prodFile = `// AUTO-GENERATED by generate-env.js. Do not edit. Do not commit.
export const environment = {
  apiUrl: ${JSON.stringify(apiUrl)},
  appEnv: ${JSON.stringify(appEnv)}
};
`;

fs.writeFileSync(path.join(folder, 'environment.ts'), devFile);
fs.writeFileSync(path.join(folder, 'environment.production.ts'), prodFile);

// Confirm it ran. We print the LENGTH, never the value itself.
console.log(`Environment files generated. apiUrl length: ${apiUrl.length} characters`);
