// Reads environment variables and writes the Angular production environment file.
// Angular cannot read GitHub Secrets by itself - this script is the bridge.

const fs = require('fs');

// process.env holds the environment variables of the current machine.
// If a variable is missing, the value after || is used instead.
const apiUrl = process.env.API_URL || 'http://localhost:3000';
const appEnv = process.env.APP_ENV || 'development';

// Build the text of the TypeScript file as a template string.
const content = `// AUTO-GENERATED by generate-env.js. Do not edit by hand.
export const environment = {
  apiUrl: '${apiUrl}',
  appEnv: '${appEnv}'
};
`;

// Write that text to disk, replacing whatever was there before.
fs.writeFileSync('src/environments/environment.production.ts', content);

// Confirm it ran. We print appEnv (safe) but never the URL or any secret.
console.log(`Environment file generated for: ${appEnv}`);
