// Creates the Angular environment files.
//
// These files are NOT stored in Git. They are generated fresh every time
// you run "npm start" or "npm run build" - including inside GitHub Actions,
// where the values come from GitHub Secrets.

const fs = require('fs');
const path = require('path');

const folder = path.join('src', 'environments');

// process.env holds the environment variables of the current machine.
// In GitHub Actions these are filled in from GitHub Secrets.
// If a variable is missing, the value after || is used instead.
const apiUrl = process.env.API_URL || 'http://localhost:3000';
const appEnv = process.env.APP_ENV || 'development';

// The folder is ignored by Git, so on a fresh clone it does not exist yet.
// "recursive: true" also means "do nothing if it is already there".
fs.mkdirSync(folder, { recursive: true });

// 1. DEVELOPMENT file - used by "npm start". Always the local JSON Server.
const devFile = `// AUTO-GENERATED by generate-env.js. Do not edit. Do not commit.
export const environment = {
  apiUrl: 'http://localhost:3000',
  appEnv: 'development'
};
`;

// 2. PRODUCTION file - used by "npm run build". Values come from above.
const prodFile = `// AUTO-GENERATED by generate-env.js. Do not edit. Do not commit.
export const environment = {
  apiUrl: '${apiUrl}',
  appEnv: '${appEnv}'
};
`;

fs.writeFileSync(path.join(folder, 'environment.ts'), devFile);
fs.writeFileSync(path.join(folder, 'environment.production.ts'), prodFile);

// Confirm it ran. We print appEnv (safe) but never the URL or any secret.
console.log(`Environment files generated. Production appEnv: ${appEnv}`);
