const fs = require('fs');
const path = require('path');

const ROOT_DIR = __dirname;
const ENVIRONMENTS_DIR = path.join(ROOT_DIR, '../src', 'environments');

function main() {
    console.log('🔄 Starting Environment Generation Process...');
    const envName = process.argv[2] || 'development';
    console.log(`📌 Target Environment: [${envName}]`);

    // Resolve the .env file
    console.log('🔍 Searching for environment variables...');
    const envFilePath = resolveEnvSourceFile(envName);

    // Parse it
    console.log('📖 Parsing environment variables...');
    const envConfig = parseEnvFile(envFilePath);

    // Generate the TS file
    console.log('⚙️ Compiling TypeScript environment files...');
    const output = `// This file is auto-generated by generate-env.js. Do not edit manually.

export const environment = {
  production: ${envName === 'production'},
  apiUrl: '${envConfig.API_BASE_URL || ''}'
};
`;

    // For local, we treat it as development for Angular's fileReplacements
    const targetEnvName = envName === 'local' ? 'development' : envName;
    const targetFilePath = path.join(ENVIRONMENTS_DIR, `environment.${targetEnvName}.ts`);
    const defaultFilePath = path.join(ENVIRONMENTS_DIR, 'environment.ts');

    if (!fs.existsSync(ENVIRONMENTS_DIR)) {
        fs.mkdirSync(ENVIRONMENTS_DIR, { recursive: true });
    }

    fs.writeFileSync(targetFilePath, output, 'utf8');
    if (targetFilePath !== defaultFilePath) {
        fs.writeFileSync(defaultFilePath, output, 'utf8');
    }

    console.log(`✅ SUCCESS: Updated environment.ts and generated environment.${targetEnvName}.ts!`);
    console.log('🚀 Environment Generation Process Complete.\n');
}

function resolveEnvSourceFile(envName) {
    const preferredPath = envName === 'local' 
        ? path.join(ROOT_DIR, '..', '.env.development') 
        : path.join(ROOT_DIR, '..', '.env.' + envName);
        
    if (fs.existsSync(preferredPath)) return preferredPath;

    const examplePath = envName === 'local' 
        ? path.join(ROOT_DIR, '..', '.env.development.example') 
        : path.join(ROOT_DIR, '..', '.env.' + envName + '.example');
        
    if (fs.existsSync(examplePath)) return examplePath;

    console.warn('Missing environment file: ' + preferredPath + ' or ' + examplePath + '. Falling back to default values.');
    return null;
}

function parseEnvFile(filePath) {
    if (!filePath) return {};
    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split(/\r?\n/);
    const config = {};

    for (const rawLine of lines) {
        const line = rawLine.trim();
        if (!line || line.startsWith('#')) continue;

        const equalsIndex = line.indexOf('=');
        if (equalsIndex === -1) continue;

        const key = line.slice(0, equalsIndex).trim();
        const value = line.slice(equalsIndex + 1).trim();
        if (key) config[key] = value;
    }
    return config;
}

main();
